export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYWU5ODViMi05ZTk3LTQ5NzUtOGZmZi1lYmJhZmRkYzg2NmUiLCJlbWFpbCI6ImFuZGVyc29uQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJBbmRlcnNvbiIsIm5iZiI6MTY5NzQ2NjMyOCwiZXhwIjoxNjk3NDk1MTI4LCJpYXQiOjE2OTc0NjYzMjgsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.CKwtktjfezL1evv_Zp5g8WA1Oa7EnwYghtkR3DzUGdE',
};