export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYWU5ODViMi05ZTk3LTQ5NzUtOGZmZi1lYmJhZmRkYzg2NmUiLCJlbWFpbCI6ImFuZGVyc29uQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJBbmRlcnNvbiIsIm5iZiI6MTY5Njk1NzExNSwiZXhwIjoxNjk2OTg1OTE1LCJpYXQiOjE2OTY5NTcxMTUsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0._lQNvj4vCexaLkUYTDhizNzwoScnDwFzNJhyIX3uQYo',
};