export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYWU5ODViMi05ZTk3LTQ5NzUtOGZmZi1lYmJhZmRkYzg2NmUiLCJlbWFpbCI6ImFuZGVyc29uQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJBbmRlcnNvbiIsIm5iZiI6MTY5NzQ2MzM4MywiZXhwIjoxNjk3NDkyMTgyLCJpYXQiOjE2OTc0NjMzODMsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.JZJpcM3Gcaf0WJ_DserXdWTzQhggal4l5trApt0LCg0',
};