export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYWU5ODViMi05ZTk3LTQ5NzUtOGZmZi1lYmJhZmRkYzg2NmUiLCJlbWFpbCI6ImFuZGVyc29uQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJBbmRlcnNvbiIsIm5iZiI6MTY5NjU1MzI5MSwiZXhwIjoxNjk2NTgyMDkxLCJpYXQiOjE2OTY1NTMyOTEsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.S3HpC9sahbKYgrlV-M4uJLGokV-T_N0Zq7pq9SaslG4',
};